import os

lines = [
    "import 'dart:async';",
    "",
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_riverpod/flutter_riverpod.dart';",
    "",
    "import '../../../core/database/app_database.dart';",
    "import '../../../shared/widgets/app_drawer.dart';",
    "import '../../clients/application/client_providers.dart';",
    "import '../application/invoice_providers.dart';",
    "import 'invoice_detail_screen.dart';",
    "import 'invoice_form_screen.dart';",
    "",
    "class InvoiceListScreen extends ConsumerStatefulWidget {",
    "  const InvoiceListScreen({super.key});",
    "",
    "  @override",
    "  ConsumerState<InvoiceListScreen> createState() =>",
    "      _InvoiceListScreenState();",
    "}",
    "",
    "class _InvoiceListScreenState extends ConsumerState<InvoiceListScreen> {",
    "  String _searchQuery = '';",
    "  Timer? _debounceTimer;",
    "",
    "  @override",
    "  void dispose() {",
    "    _debounceTimer?.cancel();",
    "    super.dispose();",
    "  }",
    "",
    "  void _onSearchChanged(String value) {",
    "    _debounceTimer?.cancel();",
    "    _debounceTimer = Timer(const Duration(milliseconds: 300), () {",
    "      if (mounted) {",
    "        setState(() {",
    "          _searchQuery = value.trim();",
    "        });",
    "      }",
    "    });",
    "  }",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    final invoicesAsync = _searchQuery.isEmpty",
    "        ? ref.watch(invoiceListProvider)",
    "        : ref.watch(invoiceSearchProvider(_searchQuery));",
    "    final clientsAsync = ref.watch(clientListProvider);",
    "",
    "    return AppDrawerScaffold(",
    "      title: '\u0627\u0644\u0641\u0648\u0627\u062a\u0648\u0631\u0627\u062a',",
    "      currentRoute: '/invoices',",
    "      child: Scaffold(",
    "        floatingActionButton: FloatingActionButton(",
    "          onPressed: () {",
    "            Navigator.push(",
    "              context,",
    "              MaterialPageRoute(",
    "                builder: (_) => const InvoiceFormScreen(),",
    "              ),",
    "            );",
    "          },",
    "          child: const Icon(Icons.add),",
    "        ),",
    "        body: Column(",
    "          children: [",
    "            Padding(",
    "              padding: const EdgeInsets.all(12),",
    "              child: TextField(",
    "                decoration: const InputDecoration(",
    "                  hintText:",
    "                      '\u0628\u062d\u062b \u0639\u0646 \u0641\u0627\u062a\u0648\u0631\u0629...',",
    "                  prefixIcon: Icon(Icons.search),",
    "                  border: OutlineInputBorder(),",
    "                ),",
    "                onChanged: _onSearchChanged,",
    "              ),",
    "            ),",
    "            Expanded(",
    "              child: invoicesAsync.when(",
    "                data: (invoices) {",
    "                  if (invoices.isEmpty) {",
    "                    return const Center(",
    "                      child: Text('\u0644\u0627 \u062a\u0648\u062c\u062f \u0641\u0627\u062a\u0648\u0631\u0627\u062a'),",
    "                    );",
    "                  }",
    "",
    "                  final clientMap = <String, Client>{};",
    "                  clientsAsync.whenData(",
    "                    (clients) {",
    "                      for (final c in clients) {",
    "                        clientMap[c.id] = c;",
    "                      }",
    "                    },",
    "                  );",
    "",
    "                  return ListView.builder(",
    "                    itemCount: invoices.length,",
    "                    itemBuilder: (context, index) {",
    "                      final invoice = invoices[index];",
    "                      final clientName =",
    "                          clientMap[invoice.clientId]?.displayName ??",
    "                              '\u0639\u0645\u064a\u0644 \u0645\u062d\u0630\u0648\u0641';",
    "                      final totalText =",
    "                          '${(invoice.total / 100).toStringAsFixed(2)} \u0631.\u064a.';",
    "                      final isVoided = invoice.status.index == 1;",
    "",
    "                      return Opacity(",
    "                        opacity: isVoided ? 0.6 : 1.0,",
    "                        child: ListTile(",
    "                          title: Text(invoice.localRef),",
    "                          subtitle: Row(",
    "                            children: [",
    "                              Text('$clientName \u2022 $totalText'),",
    "                              if (isVoided) ...[",
    "                                const SizedBox(width: 8),",
    "                                const Text('\u0645\u0644\u063a\u064a\u0629',",
    "                                    style: TextStyle(color: Colors.red)),",
    "                              ],",
    "                            ],",
    "                          ),",
    "                          onTap: () {",
    "                            Navigator.push(",
    "                              context,",
    "                              MaterialPageRoute(",
    "                                builder: (_) => InvoiceDetailScreen(",
    "                                  invoiceId: invoice.id,",
    "                                ),",
    "                              ),",
    "                            );",
    "                          },",
    "                        ),",
    "                      );",
    "                    },",
    "                  );",
    "                },",
    "                loading: () => const Center(",
    "                  child: CircularProgressIndicator(),",
    "                ),",
    "                error: (e, _) => Center(",
    "                  child: Text(e.toString()),",
    "                ),",
    "              ),",
    "            ),",
    "          ],",
    "        ),",
    "      ),",
    "    );",
    "  }",
    "}",
]

content = '\n'.join(lines) + '\n'
outpath = os.path.join(
    r'D:\Motaz_App2\motaz_app\motaz_app_flutter\lib\features\invoices\presentation',
    'invoice_list_screen.dart',
)
os.makedirs(os.path.dirname(outpath), exist_ok=True)
with open(outpath, 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)
print('T012 invoice_list_screen.dart written.')
