import os

lines = [
    "import 'dart:async';",
    "",
    "import 'package:drift/drift.dart';",
    "import 'package:flutter_riverpod/flutter_riverpod.dart';",
    "import 'package:motaz_app_client/motaz_app_client.dart' as server;",
    "",
    "import '../../../core/connectivity/connectivity_provider.dart';",
    "import '../../../core/database/app_database.dart' hide Client;",
    "import '../../../core/database/database_provider.dart';",
    "import '../../../core/database/device_service.dart';",
    "import '../../../core/database/device_provider.dart';",
    "import '../../../core/server/server_client_provider.dart';",
    "import '../../../core/database/enums/enums.dart';",
    "import '../domain/sync_state.dart';",
    "import 'sync_coordinator.dart';",
    "",
    "final syncCoordinatorProvider = Provider<SyncCoordinator>((ref) {",
    "  final db = ref.watch(appDatabaseProvider);",
    "  final serverClient = ref.watch(serverpodClientProvider);",
    "  final deviceService = ref.watch(deviceServiceProvider);",
    "  final connectivityAsync = ref.watch(connectivityProvider);",
    "  final connectivityStream = connectivityAsync.when(",
    "    data: (status) => Stream.value(status),",
    "    loading: () => Stream.value(ConnectivityStatus.offline),",
    "    error: (_, __) => Stream.value(ConnectivityStatus.offline),",
    "  );",
    "  final coordinator = SyncCoordinator(",
    "    db: db,",
    "    serverClient: serverClient,",
    "    deviceService: deviceService,",
    "    connectivityStream: connectivityStream,",
    "  );",
    "  ref.onDispose(coordinator.dispose);",
    "  return coordinator;",
    "});",
    "",
    "final syncStateProvider = StreamProvider<SyncState>((ref) {",
    "  final coordinator = ref.watch(syncCoordinatorProvider);",
    "  return coordinator.stateStream;",
    "});",
    "",
    "final pendingCountProvider = StreamProvider<int>((ref) {",
    "  final db = ref.watch(appDatabaseProvider);",
    "  final query = db.select(db.syncOutbox)",
    "    ..where((t) => t.status.equals(SyncOutboxStatus.PENDING.index));",
    "  return query.watch().map((event) {",
    "    int count = 0;",
    "    for (final row in event) {",
    "      count++;",
    "    }",
    "    return count;",
    "  });",
    "});",
    "",
    "final unresolvedConflictCountProvider = StreamProvider<int>((ref) {",
    "  final db = ref.watch(appDatabaseProvider);",
    "  final query = db.select(db.conflictLogs)",
    "    ..where((t) => t.resolutionStatus.equals(ConflictStatus.PENDING.index));",
    "  return query.watch().map((event) {",
    "    int count = 0;",
    "    for (final row in event) {",
    "      count++;",
    "    }",
    "    return count;",
    "  });",
    "});",
]

outpath = r'D:\Motaz_App2\motaz_app\motaz_app_flutter\lib\features\sync\application\sync_providers.dart'
with open(outpath, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(lines) + '\n')
print(f"OK: {len(lines)} lines -> {outpath}")
