import os

lines = [
    "import 'dart:convert';",
    "",
    "import 'package:drift/drift.dart';",
    "import 'package:uuid/uuid.dart';",
    "",
    "import '../../../core/database/app_database.dart';",
    "import '../../../core/database/enums/audit_operation.dart';",
    "import '../../../core/database/enums/parent_entity_type.dart';",
    "import '../../../core/database/enums/record_status.dart';",
    "import '../../../core/database/enums/receipt_type.dart';",
    "import '../../../core/database/enums/sync_outbox_status.dart';",
    "import '../../../core/database/enums/sync_status.dart';",
    "import 'receipt_allocator.dart';",
    "",
    "class ReceiptRepository {",
    "  ReceiptRepository(this._db);",
    "",
    "  final AppDatabase _db;",
    "  final _uuid = const Uuid();",
]

# --- T006: createInvoiceLinked + query methods ---
lines += [
    "",
    "  Future<Receipt> createInvoiceLinked({",
    "    required String clientId,",
    "    required String invoiceId,",
    "    required int amount,",
    "    required DateTime receiptDate,",
    "    String? note,",
    "    required String deviceId,",
    "  }) async {",
    "    if (amount <= 0) {",
    "      throw ArgumentError('Amount must be positive');",
    "    }",
    "",
    "    final invoice = await (_db.select(_db.salesInvoices)",
    "          ..where((t) => t.id.equals(invoiceId))).getSingle();",
    "",
    "    if (invoice.status == RecordStatus.VOIDED) {",
    "      throw StateError('Cannot create receipt for a voided invoice');",
    "    }",
    "",
    "    if (invoice.clientId != clientId) {",
    "      throw ArgumentError('Invoice does not belong to the specified client');",
    "    }",
    "",
    "    final collectedRow = await _db.customSelect(",
    "      'SELECT COALESCE(SUM(ra.allocated_amount), 0) AS collected '",
    "      'FROM receipt_allocations ra '",
    "      'INNER JOIN receipts r ON ra.receipt_id = r.id '",
    "      'WHERE ra.invoice_id = ? AND r.status = ?',",
    "      variables: [",
    "        Variable(invoiceId),",
    "        Variable(RecordStatus.ACTIVE.index),",
    "      ],",
    "    ).getSingle();",
    "    final collected = collectedRow.read<int>('collected');",
    "    final remainingBalance = invoice.total - collected;",
    "",
    "    if (amount > remainingBalance) {",
    "      throw ArgumentError(",
    "        'Amount ($amount) exceeds remaining balance ($remainingBalance)',",
    "      );",
    "    }",
    "",
    "    final receiptId = _uuid.v4();",
    "    final now = DateTime.now();",
    "",
    "    await _db.transaction(() async {",
    "      await _db.into(_db.receipts).insert(",
    "        ReceiptsCompanion(",
    "          id: Value(receiptId),",
    "          receiptType: Value(ReceiptType.INVOICE_LINKED),",
    "          clientId: Value(clientId),",
    "          invoiceId: Value(invoiceId),",
    "          amount: Value(amount),",
    "          receiptDate: Value(receiptDate),",
    "          note: Value(note),",
    "          status: Value(RecordStatus.ACTIVE),",
    "          voidReason: Value.absent(),",
    "          createdAt: Value(now),",
    "          updatedAt: Value(now),",
    "          deviceId: Value(deviceId),",
    "          rowVersion: const Value(1),",
    "          syncStatus: Value(SyncStatus.PENDING),",
    "        ),",
    "      );",
    "",
    "      final allocationId = _uuid.v4();",
    "      await _db.into(_db.receiptAllocations).insert(",
    "        ReceiptAllocationsCompanion(",
    "          id: Value(allocationId),",
    "          receiptId: Value(receiptId),",
    "          invoiceId: Value(invoiceId),",
    "          allocatedAmount: Value(amount),",
    "          createdAt: Value(now),",
    "          updatedAt: Value(now),",
    "        ),",
    "      );",
    "",
    "      final receiptPayload = jsonEncode({",
    "        'id': receiptId,",
    "        'receiptType': ReceiptType.INVOICE_LINKED.index,",
    "        'clientId': clientId,",
    "        'invoiceId': invoiceId,",
    "        'amount': amount,",
    "        'receiptDate': receiptDate.toIso8601String(),",
    "        'note': note,",
    "        'status': RecordStatus.ACTIVE.index,",
    "        'voidReason': null,",
    "        'createdAt': now.toIso8601String(),",
    "        'updatedAt': now.toIso8601String(),",
    "        'deviceId': deviceId,",
    "        'rowVersion': 1,",
    "        'syncStatus': SyncStatus.PENDING.index,",
    "      });",
    "      await _db.into(_db.syncOutbox).insert(",
    "        SyncOutboxCompanion.insert(",
    "          id: _uuid.v4(),",
    "          entityType: ParentEntityType.RECEIPT,",
    "          entityId: receiptId,",
    "          operation: AuditOperation.CREATE,",
    "          payload: receiptPayload,",
    "          rowVersion: 1,",
    "          deviceId: deviceId,",
    "          createdAt: now,",
    "          status: Value(SyncOutboxStatus.PENDING),",
    "        ),",
    "      );",
    "",
    "      final allocPayload = jsonEncode({",
    "        'id': allocationId,",
    "        'receiptId': receiptId,",
    "        'invoiceId': invoiceId,",
    "        'allocatedAmount': amount,",
    "        'createdAt': now.toIso8601String(),",
    "        'updatedAt': now.toIso8601String(),",
    "      });",
    "      await _db.into(_db.syncOutbox).insert(",
    "        SyncOutboxCompanion.insert(",
    "          id: _uuid.v4(),",
    "          entityType: ParentEntityType.RECEIPT_ALLOCATION,",
    "          entityId: allocationId,",
    "          operation: AuditOperation.CREATE,",
    "          payload: allocPayload,",
    "          rowVersion: 1,",
    "          deviceId: deviceId,",
    "          createdAt: now,",
    "          status: Value(SyncOutboxStatus.PENDING),",
    "        ),",
    "      );",
    "    });",
    "",
    "    return await getById(receiptId);",
    "  }",
]

# --- T007: createGeneral method ---
lines += [
    "",
    "  Future<Receipt> createGeneral({",
    "    required String clientId,",
    "    required int amount,",
    "    required DateTime receiptDate,",
    "    String? note,",
    "    required String deviceId,",
    "  }) async {",
    "    if (amount <= 0) {",
    "      throw ArgumentError('Amount must be positive');",
    "    }",
    "",
    "    final receiptId = _uuid.v4();",
    "    final now = DateTime.now();",
    "    final allocator = ReceiptAllocator(_db);",
    "    final allocations = await allocator.allocateFifo(clientId, amount);",
    "",
    "    await _db.transaction(() async {",
    "      await _db.into(_db.receipts).insert(",
    "        ReceiptsCompanion(",
    "          id: Value(receiptId),",
    "          receiptType: Value(ReceiptType.GENERAL),",
    "          clientId: Value(clientId),",
    "          invoiceId: Value.absent(),",
    "          amount: Value(amount),",
    "          receiptDate: Value(receiptDate),",
    "          note: Value(note),",
    "          status: Value(RecordStatus.ACTIVE),",
    "          voidReason: Value.absent(),",
    "          createdAt: Value(now),",
    "          updatedAt: Value(now),",
    "          deviceId: Value(deviceId),",
    "          rowVersion: const Value(1),",
    "          syncStatus: Value(SyncStatus.PENDING),",
    "        ),",
    "      );",
    "",
    "      for (final alloc in allocations) {",
    "        final allocWithReceipt = alloc.copyWith(",
    "          receiptId: Value(receiptId),",
    "        );",
    "        await _db.into(_db.receiptAllocations).insert(allocWithReceipt);",
    "",
    "        final allocId = allocWithReceipt.id.value;",
    "        final allocPayload = jsonEncode({",
    "          'id': allocId,",
    "          'receiptId': receiptId,",
    "          'invoiceId': allocWithReceipt.invoiceId.value,",
    "          'allocatedAmount': allocWithReceipt.allocatedAmount.value,",
    "          'createdAt': now.toIso8601String(),",
    "          'updatedAt': now.toIso8601String(),",
    "        });",
    "        await _db.into(_db.syncOutbox).insert(",
    "          SyncOutboxCompanion.insert(",
    "            id: _uuid.v4(),",
    "            entityType: ParentEntityType.RECEIPT_ALLOCATION,",
    "            entityId: allocId,",
    "            operation: AuditOperation.CREATE,",
    "            payload: allocPayload,",
    "            rowVersion: 1,",
    "            deviceId: deviceId,",
    "            createdAt: now,",
    "            status: Value(SyncOutboxStatus.PENDING),",
    "          ),",
    "        );",
    "      }",
    "",
    "      final receiptPayload = jsonEncode({",
    "        'id': receiptId,",
    "        'receiptType': ReceiptType.GENERAL.index,",
    "        'clientId': clientId,",
    "        'invoiceId': null,",
    "        'amount': amount,",
    "        'receiptDate': receiptDate.toIso8601String(),",
    "        'note': note,",
    "        'status': RecordStatus.ACTIVE.index,",
    "        'voidReason': null,",
    "        'createdAt': now.toIso8601String(),",
    "        'updatedAt': now.toIso8601String(),",
    "        'deviceId': deviceId,",
    "        'rowVersion': 1,",
    "        'syncStatus': SyncStatus.PENDING.index,",
    "      });",
    "      await _db.into(_db.syncOutbox).insert(",
    "        SyncOutboxCompanion.insert(",
    "          id: _uuid.v4(),",
    "          entityType: ParentEntityType.RECEIPT,",
    "          entityId: receiptId,",
    "          operation: AuditOperation.CREATE,",
    "          payload: receiptPayload,",
    "          rowVersion: 1,",
    "          deviceId: deviceId,",
    "          createdAt: now,",
    "          status: Value(SyncOutboxStatus.PENDING),",
    "        ),",
    "      );",
    "    });",
    "",
    "    return await getById(receiptId);",
    "  }",
]

# --- T008: voidReceipt method ---
lines += [
    "",
    "  Future<void> voidReceipt(String id, String reason, String deviceId) async {",
    "    if (reason.trim().isEmpty) {",
    "      throw ArgumentError('Void reason is required');",
    "    }",
    "",
    "    final existing = await getById(id);",
    "",
    "    if (existing.status == RecordStatus.VOIDED) {",
    "      throw StateError('Receipt is already voided');",
    "    }",
    "",
    "    final now = DateTime.now();",
    "    final newVersion = existing.rowVersion + 1;",
    "",
    "    await _db.transaction(() async {",
    "      await (_db.delete(_db.receiptAllocations)",
    "            ..where((t) => t.receiptId.equals(id))).go();",
    "",
    "      await (_db.update(_db.receipts)",
    "            ..where((t) => t.id.equals(id))).write(",
    "        ReceiptsCompanion(",
    "          status: Value(RecordStatus.VOIDED),",
    "          voidReason: Value(reason),",
    "          updatedAt: Value(now),",
    "          rowVersion: Value(newVersion),",
    "          syncStatus: Value(SyncStatus.PENDING),",
    "        ),",
    "      );",
    "",
    "      final receiptPayload = jsonEncode({",
    "        'id': id,",
    "        'receiptType': existing.receiptType.index,",
    "        'clientId': existing.clientId,",
    "        'invoiceId': existing.invoiceId,",
    "        'amount': existing.amount,",
    "        'receiptDate': existing.receiptDate.toIso8601String(),",
    "        'note': existing.note,",
    "        'status': RecordStatus.VOIDED.index,",
    "        'voidReason': reason,",
    "        'createdAt': existing.createdAt.toIso8601String(),",
    "        'updatedAt': now.toIso8601String(),",
    "        'deviceId': existing.deviceId,",
    "        'rowVersion': newVersion,",
    "        'syncStatus': SyncStatus.PENDING.index,",
    "      });",
    "      await _db.into(_db.syncOutbox).insert(",
    "        SyncOutboxCompanion.insert(",
    "          id: _uuid.v4(),",
    "          entityType: ParentEntityType.RECEIPT,",
    "          entityId: id,",
    "          operation: AuditOperation.UPDATE,",
    "          payload: receiptPayload,",
    "          rowVersion: newVersion,",
    "          deviceId: deviceId,",
    "          createdAt: now,",
    "          status: Value(SyncOutboxStatus.PENDING),",
    "        ),",
    "      );",
    "    });",
    "  }",
]

# --- Query methods (from T006 scope) ---
lines += [
    "",
    "  Future<Receipt> getById(String id) async {",
    "    return (_db.select(_db.receipts)..where((t) => t.id.equals(id)))",
    "        .getSingle();",
    "  }",
    "",
    "  Stream<List<Receipt>> watchAll() {",
    "    return (_db.select(_db.receipts)",
    "          ..orderBy([",
    "            (t) => OrderingTerm.desc(t.receiptDate),",
    "            (t) => OrderingTerm.desc(t.createdAt),",
    "          ])).watch();",
    "  }",
    "",
    "  Future<List<ReceiptAllocation>> getAllocationsForReceipt(",
    "    String receiptId,",
    "  ) async {",
    "    return (_db.select(_db.receiptAllocations)",
    "          ..where((t) => t.receiptId.equals(receiptId))).get();",
    "  }",
    "}",
]

content = '\n'.join(lines) + '\n'

outpath = r'D:\Motaz_App2\motaz_app\motaz_app_flutter\lib\features\receipts\data\receipt_repository.dart'
os.makedirs(os.path.dirname(outpath), exist_ok=True)

with open(outpath, 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)

print('T006-T008 receipt_repository.dart written successfully.')
