import os

lines = [
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_riverpod/flutter_riverpod.dart';",
    "",
    "import '../../../core/database/app_database.dart';",
    "import '../../../core/database/device_service.dart';",
    "import '../../../core/database/enums/record_status.dart';",
    "import '../application/invoice_providers.dart';",
    "import '../../clients/application/client_providers.dart';",
    "import '../../products/application/product_providers.dart';",
    "import '../../receipts/presentation/receipt_form_screen.dart';",
    "import 'invoice_form_screen.dart';",
    "",
    "class InvoiceDetailScreen extends ConsumerStatefulWidget {",
    "  const InvoiceDetailScreen({super.key, required this.invoiceId});",
    "",
    "  final String invoiceId;",
    "",
    "  @override",
    "  ConsumerState<InvoiceDetailScreen> createState() =>",
    "      _InvoiceDetailScreenState();",
    "}",
    "",
    "class _InvoiceDetailScreenState extends ConsumerState<InvoiceDetailScreen> {",
    "  SalesInvoice? _invoice;",
    "  List<SalesInvoiceLine> _lines = [];",
    "  List<Receipt> _receipts = [];",
    "  Client? _client;",
    "  int _collectedAmount = 0;",
    "  int _remainingBalance = 0;",
    "  bool _hasReceipts = false;",
    "  bool _hasReturns = false;",
    "  bool _loading = true;",
    "  Map<String, String> _productNames = {};",
    "",
    "  @override",
    "  void initState() {",
    "    super.initState();",
    "    _loadData();",
    "  }",
    "",
    "  Future<void> _loadData() async {",
    "    final repo = ref.read(invoiceRepositoryProvider);",
    "    final clientRepo = ref.read(clientRepositoryProvider);",
    "    try {",
    "      final invoice = await repo.getById(widget.invoiceId);",
    "      final lines = await repo.getLinesForInvoice(widget.invoiceId);",
    "      final receipts = await repo.getReceiptsForInvoice(widget.invoiceId);",
    "      final collected = await repo.getCollectedAmount(widget.invoiceId);",
    "      final remaining = await repo.getRemainingBalance(widget.invoiceId);",
    "      final hasR = await repo.hasActiveReceipts(widget.invoiceId);",
    "      final hasRet = await repo.hasActiveReturns(widget.invoiceId);",
    "",
    "      Client? client;",
    "      try {",
    "        client = await clientRepo.getById(invoice.clientId);",
    "      } catch (_) {",
    "        client = null;",
    "      }",
    "",
    "      final productIds = lines.map((l) => l.productId).toSet();",
    "      final db = ref.read(appDatabaseProvider);",
    "      final products = await (db.select(db.products)).get();",
    "      final pMap = {for (final p in products) p.id: p.name};",
    "",
    "      if (mounted) {",
    "        setState(() {",
    "          _invoice = invoice;",
    "          _lines = lines;",
    "          _receipts = receipts;",
    "          _collectedAmount = collected;",
    "          _remainingBalance = remaining;",
    "          _hasReceipts = hasR;",
    "          _hasReturns = hasRet;",
    "          _client = client;",
    "          _productNames = pMap;",
    "          _loading = false;",
    "        });",
    "      }",
    "    } catch (e) {",
    "      if (mounted) {",
    "        setState(() => _loading = false);",
    "      }",
    "    }",
    "  }",
    "",
    "  String _formatMoney(int minorUnits) {",
    "    return '${(minorUnits / 100).toStringAsFixed(2)} ر.ي.';",
    "  }",
    "",
    "  Future<void> _voidInvoice(String reason) async {",
    "    final device = await ref.read(deviceServiceProvider).ensureCurrentDevice();",
    "    final repo = ref.read(invoiceRepositoryProvider);",
    "    await repo.voidInvoice(widget.invoiceId, reason, device.id);",
    "    if (mounted) {",
    "      ScaffoldMessenger.of(context).showSnackBar(",
    "        const SnackBar(content: Text('تم إلغاء الفاتورة')),",
    "      );",
    "      _loadData();",
    "    }",
    "  }",
    "",
    "  Future<void> _showVoidDialog() async {",
    "    final reasonController = TextEditingController();",
    "    final confirmed = await showDialog<bool>(",
    "      context,",
    "      AlertDialog(",
    "        title: const Text('إلغاء الفاتورة'),",
    "        content: Column(",
    "          mainAxisSize: MainAxisSize.min, 4),",
    "          children: [",
    "            TextField(",
    "              controller: reasonController,",
    "              decoration: const InputDecoration(",
    "                labelText: 'سبب الإلغاء *',",
    "                hintText: 'أدخل سبب الإلغاء',",
    "              ),",
    "              maxLines: 3,",
    "            ),",
    "          ],",
    "        ),",
    "        actions: [",
    "          TextButton(",
    "            onPressed: () {",
    "              Navigator.of(context).pop();",
    "              if (reasonController.text.trim().isNotEmpty) {",
    "                _voidInvoice(reasonController.text.trim());",
    "              }",
    "            },",
    "            child: Text('إلغاء'),",
    "          ),",
    "          TextButton(",
    "            onPressed: () => Navigator.of(context).pop(),",
    "            child: Text('تراجع'),",
    "          ),",
    "        ],",
    "      );",
    "    );",
    "    if (confirmed) reasonController.dispose();",
    "  }",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    if (_loading) {",
    "      return const Scaffold(",
    "        appBar: AppBar(title: const Text('تفاصيل الفاتورة')),",
    "        body: const Center(child: CircularProgressIndicator()),",
    "      );",
    "    }",
    "",
    "    final invoice = _invoice!;",
    "    final isActive = invoice.status == RecordStatus.ACTIVE;",
    "",
    "    return Scaffold(",
    "      appBar: AppBar(",
    "        title: Text(invoice.localRef),",
    "      ),",
    "      body: SingleChildScrollView(",
    "        padding: const EdgeInsets.all(16),",
    "        child: Column(",
    "          crossAxisAlignment: CrossAxisAlignment.stretch,",
    "          children: [",
    "            Card(",
    "              child: Padding(",
    "                padding: const EdgeInsets.all(16),",
    "                child: Column(",
    "                  crossAxisAlignment: CrossAxisAlignment.start,",
    "                  children: [",
    "                    Text(",
    "                      'معلومات الفاتورة',",
    "                      style: Theme.of(context).textTheme.titleMedium,",
    "                    ),",
    "                    const SizedBox(height: 12),",
    "                    if (_client != null)",
    "                      Text('العميل: ${_client!.displayName}'),",
    "                    Text('التاريخ: ${invoice.invoiceDate.toIso8601String().split(' ').first}'),",
    "                    if (invoice.note != null)",
    "                      Padding(",
    "                        padding: const EdgeInsets.only(top: 4),",
    "                        child: Text('ملاحظة: ${invoice.note}'),",
    "                      ),",
    "                    const SizedBox(height: 8),",
    "                    Row(",
    "                      children: [",
    "                        Text('الحالة: '),",
    "                        if (isActive) ...[",
    "                          Container(",
    "                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),",
    "                            decoration: BoxDecoration(",
    "                              color: Colors.green.withValues(alpha: 0.2),",
    "                              borderRadius: BorderRadius.circular(4),",
    "                            ),",
    "                            child: const Text('نشطة', style: TextStyle(color: Colors.green)),",
    "                          ),",
    "                        ] else ...[",
    "                          Container(",
    "                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),",
    "                            decoration: BoxDecoration(",
    "                              color: Colors.red.withValues(alpha: 0.2),",
    "                              borderRadius: BorderRadius.circular(4),",
    "                            ),",
    "                            child: Text(",
    "                              'ملغية${invoice.voidReason != null ? ' - ${invoice.voidReason}' : ''}',",
    "                              style: const TextStyle(color: Colors.red),",
    "                            ),",
    "                          ),",
    "                        ],",
    "                      ],",
    "                    ),",
    "                  ],",
    "                ),",
    "              ),",
    "            ),",
    "            const SizedBox(height: 16),",
    "            Card(",
    "              child: Padding(",
    "                padding: const EdgeInsets.all(16),",
    "                child: Column(",
    "                  crossAxisAlignment: CrossAxisAlignment.start,",
    "                  children: [",
    "                    Text(",
    "                      'البنود',",
    "                      style: Theme.of(context).textTheme.titleMedium,",
    "                    ),",
    "                    const SizedBox(height: 12),",
    "                    ..._lines.asMap((line) => ListTile(",
    "                          dense: true,",
    "                          title: Text(_productNames[line.productId] ?? 'منتج غير معروف'),",
    "                          subtitle: Text(",
    "                            '${line.quantity} × ${_formatMoney(line.unitPrice)} = ${_formatMoney(line.lineTotal)}',",
    "                          ),",
    "                        ),",
    "                    if (invoice.discount > 0) ...[",
    "                      const Divider(),",
    "                      Padding(",
    "                        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),",
    "                        child: Row(",
    "                          mainAxisAlignment: MainAxisAlignment.spaceBetween,",
    "                          children: [",
    "                            const Text('الخصم:'),",
    "                            Text(_formatMoney(invoice.discount)),",
    "                          ],",
    "                        ),",
    "                      ),",
    "                    ],",
    "                    const Divider(),",
    "                    Padding(",
    "                      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),",
    "                      child: Row(",
    "                        mainAxisAlignment: MainAxisAlignment.spaceBetween,",
    "                        children: [",
    "                          Text('الإجمالي:', style: Theme.of(context).textTheme.titleMedium),",
    "                          Text(",
    "                            _formatMoney(invoice.total),",
    "                            style: Theme.of(context).textTheme.titleMedium,",
    "                          ),",
    "                        ],",
    "                      ),",
    "                    ],",
    "                ),",
    "            ),",
    "            const SizedBox(height: 16),",
    "            Card(",
    "              child: Padding(",
    "                padding: const EdgeInsets.all(16),",
    "                child: Column(",
    "                  crossAxisAlignment: CrossAxisAlignment.start,",
    "                  children: [",
    "                    Text(",
    "                      'المدفوعات',",
    "                      style: Theme.of(context).textTheme.titleMedium,",
    "                    ),",
    "                    const SizedBox(height: 12),",
    "                    if (_receipts.isEmpty)",
    "                      const Padding(",
    "                        padding: const EdgeInsets.symmetric(vertical: 8),",
    "                        child: const Text('لا توجد دفعات'),",
    "                      )",
    "                    else",
    "                      ..._receipts.map((r) => ListTile(",
    "                        dense: true,",
    "                        title: Text(",
    "                          r.receiptType == ReceiptType.INVOICE_LINKED",
    "                              ? 'دفعة مرتبطة بفاتورة'"
    "                              : 'دفعة عامة',",
    "                        ),",
    "                        subtitle: Text(",
    "                          '${_formatMoney(r.amount)} - ${r.receiptDate.toIso8601String().split(' ').first}',",
    "                        ),",
    "                      ),",
    "                    const Divider(),",
    "                    Padding(",
    "                      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),",
    "                      child: Row(",
    "                        mainAxisAlignment: MainAxisAlignment.spaceBetween,",
    "                        children: [",
    "                          const Text('المحصل:'),",
    "                          Text(_formatMoney(_collectedAmount)),",
    "                        ],",
    "                      ),",
    "                    Padding(",
    "                      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),",
    "                      child: Row(",
    "                        mainAxisAlignment: MainAxisAlignment.spaceBetween,",
    "                        children: [",
    "                          const Text('المبلغ المتبقي:'),",
    "                          Text(",
    "                            _formatMoney(_remainingBalance),",
    "                            style: TextStyle(",
    "                              color: _remainingBalance > 0 ? Colors.red : Colors.green,",
    "                            ),",
    "                          ),",
    "                        ],",
    "                      ),",
    "                    ],",
    "                  ],",
    "                ),",
    "              ),",
    "            ),",
    "            if (isActive) ...[",
    "              const SizedBox(height: 16),",
    "              Row(",
    "                children: [",
    "                  Expanded(",
    "                    child: OutlinedButton.icon(",
    "                      onPressed: () async {",
    "                        await Navigator.push(",
    "                          context,",
    "                          MaterialPageRoute(",
    "                            builder: (_) => const InvoiceFormScreen(),",
    "                          ),",
    "                        );",
    "                        if (mounted) _loadData();",
    "                      },",
    "                      icon: const Icon(Icons.edit),",
    "                      label: const Text('تعديل'),",
    "                    ),",
    "                  ),",
    "                  if (_remainingBalance > 0)",
    "                    Expanded(",
    "                      child: OutlinedButton.icon(",
    "                        onPressed: () {",
    "                          Navigator.push(",
    "                            context,",
    "                            MaterialPageRoute(",
    "                              builder: (_) => const ReceiptFormScreen(),",
    "                            ),",
    "                          );",
    "                          if (mounted) _loadData();",
    "                        });",
    "                        icon: const Icon(Icons.add_card),",
    "                        label: const Text('إضافة دفعة'),",
    "                      ),",
    "                    ),",
    "                  Expanded(",
    "                    child: OutlinedButton.icon(",
    "                      onPressed: _showVoidDialog,",
    "                      icon: const Icon(Icons.cancel),",
    "                      label: const Text('إلغاء الفاتورة'),",
    "                      style: const ButtonStyle(foregroundColor: Colors.red),",
    "                    ),",
    "                  ),",
    "                ],",
    "              ),",
    "            ],",
    "          ],",
    "        ),",
    "      ),",
    "    );",
    "  }",
    "}",
]

content = '\n'.join(lines) + '\n'

outpath = r'D:\Motaz_App2\motaz_app\motaz_app_flutter\lib\features\invoices\presentation\invoice_detail_screen.dart'
os.makedirs(os.path.dirname(outpath), exist_ok=True)
with open(outpath, 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)

print('T013 invoice_detail_screen.dart written.')
