import os

lines = [
    "import 'dart:convert';",
    "",
    "import 'package:drift/drift.dart';",
    "import 'package:uuid/uuid.dart';",
    "",
    "import '../../../core/database/app_database.dart';",
    "import '../../../core/database/enums/audit_operation.dart';",
    "import '../../../core/database/enums/parent_entity_type.dart';",
    "import '../../../core/database/enums/record_status.dart';",
    "import '../../../core/database/enums/receipt_type.dart';",
    "import '../../../core/database/enums/sync_outbox_status.dart';",
    "import '../../../core/database/enums/sync_status.dart';",
    "import '../../receipts/data/receipt_allocator.dart';",
    "",
    "class InvoiceRepository {",
    "  InvoiceRepository(this._db);",
    "",
    "  final AppDatabase _db;",
    "  final _uuid = const Uuid();",
]

# --- T002: create method ---
lines += [
    "",
    "  Future<SalesInvoice> create({",
    "    required String clientId,",
    "    required DateTime invoiceDate,",
    "    required int discount,",
    "    required String note,",
    "    required List<SalesInvoiceLinesCompanion> lines,",
    "    required int paidAmount,",
    "    required String deviceId,",
    "  }) async {",
    "    if (lines.isEmpty) {",
    "      throw ArgumentError('Invoice must have at least one line');",
    "    }",
    "    if (paidAmount < 0) {",
    "      throw ArgumentError('Paid amount cannot be negative');",
    "    }",
    "",
    "    var subtotal = 0;",
    "    final preparedLines = <SalesInvoiceLinesCompanion>[];",
    "    for (int i = 0; i < lines.length; i++) {",
    "      final line = lines[i];",
    "      final qty = line.quantity.present ? line.quantity.value : 1;",
    "      final price = line.unitPrice.present ? line.unitPrice.value : 0;",
    "      final lineTotal = qty * price;",
    "      preparedLines.add(line.copyWith(",
    "        lineTotal: Value(lineTotal),",
    "      ));",
    "      subtotal += lineTotal;",
    "    }",
    "",
    "    if (discount > subtotal) {",
    "      throw ArgumentError('Discount cannot exceed subtotal');",
    "    }",
    "",
    "    final total = subtotal - discount;",
    "",
    "    if (paidAmount > total) {",
    "      throw ArgumentError('Paid amount cannot exceed total');",
    "    }",
    "",
    "    final device = await (_db.select(_db.devices)",
    "          ..where((t) => t.id.equals(deviceId))).getSingle();",
    "    final sequence = device.nextInvoiceSequence;",
    "    final localRef =",
    "        'INV-${device.deviceCode}-${sequence.toString().padLeft(3, '0')}';",
    "",
    "    final invoiceId = _uuid.v4();",
    "    final now = DateTime.now();",
    "",
    "    await _db.transaction(() async {",
    "      await _db.into(_db.salesInvoices).insert(",
    "        SalesInvoicesCompanion(",
    "          id: Value(invoiceId),",
    "          localRef: Value(localRef),",
    "          officialNo: Value.absent(),",
    "          clientId: Value(clientId),",
    "          invoiceDate: Value(invoiceDate),",
    "          discount: Value(discount),",
    "          total: Value(total),",
    "          note: Value(note.isEmpty ? null : note),",
    "          status: Value(RecordStatus.ACTIVE),",
    "          voidReason: Value.absent(),",
    "          createdAt: Value(now),",
    "          updatedAt: Value(now),",
    "          deviceId: Value(deviceId),",
    "          rowVersion: const Value(1),",
    "          syncStatus: Value(SyncStatus.PENDING),",
    "        ),",
    "      );",
    "",
    "      for (final line in preparedLines) {",
    "        final lineId = _uuid.v4();",
    "        await _db.into(_db.salesInvoiceLines).insert(",
    "          line.copyWith(",
    "            id: Value(lineId),",
    "            invoiceId: Value(invoiceId),",
    "            createdAt: Value(now),",
    "            updatedAt: Value(now),",
    "          ),",
    "        );",
    "",
    "        final linePayload = jsonEncode({",
    "          'id': lineId,",
    "          'invoiceId': invoiceId,",
    "          'productId': line.productId.present ? line.productId.value : null,",
    "          'quantity': line.quantity.present ? line.quantity.value : null,",
    "          'unitPrice': line.unitPrice.present ? line.unitPrice.value : null,",
    "          'lineTotal': line.lineTotal.present ? line.lineTotal.value : null,",
    "          'createdAt': now.toIso8601String(),",
    "          'updatedAt': now.toIso8601String(),",
    "        });",
    "        await _db.into(_db.syncOutbox).insert(",
    "          SyncOutboxCompanion.insert(",
    "            id: _uuid.v4(),",
    "            entityType: ParentEntityType.SALES_INVOICE_LINE,",
    "            entityId: lineId,",
    "            operation: AuditOperation.CREATE,",
    "            payload: linePayload,",
    "            rowVersion: 1,",
    "            deviceId: deviceId,",
    "            createdAt: now,",
    "            status: Value(SyncOutboxStatus.PENDING),",
    "          ),",
    "        );",
    "      }",
    "",
    "      await (_db.update(_db.devices)",
    "            ..where((t) => t.id.equals(deviceId))).write(",
    "        DevicesCompanion(",
    "          nextInvoiceSequence: Value(sequence + 1),",
    "        ),",
    "      );",
    "",
    "      final invoicePayload = jsonEncode({",
    "        'id': invoiceId,",
    "        'localRef': localRef,",
    "        'officialNo': null,",
    "        'clientId': clientId,",
    "        'invoiceDate': invoiceDate.toIso8601String(),",
    "        'discount': discount,",
    "        'total': total,",
    "        'note': note.isEmpty ? null : note,",
    "        'status': RecordStatus.ACTIVE.index,",
    "        'voidReason': null,",
    "        'createdAt': now.toIso8601String(),",
    "        'updatedAt': now.toIso8601String(),",
    "        'deviceId': deviceId,",
    "        'rowVersion': 1,",
    "        'syncStatus': SyncStatus.PENDING.index,",
    "      });",
    "      await _db.into(_db.syncOutbox).insert(",
    "        SyncOutboxCompanion.insert(",
    "          id: _uuid.v4(),",
    "          entityType: ParentEntityType.SALES_INVOICE,",
    "          entityId: invoiceId,",
    "          operation: AuditOperation.CREATE,",
    "          payload: invoicePayload,",
    "          rowVersion: 1,",
    "          deviceId: deviceId,",
    "          createdAt: now,",
    "          status: Value(SyncOutboxStatus.PENDING),",
    "        ),",
    "      );",
    "",
    "      if (paidAmount > 0) {",
    "        final receiptId = _uuid.v4();",
    "        final receiptPayload = jsonEncode({",
    "          'id': receiptId,",
    "          'receiptType': ReceiptType.INVOICE_LINKED.index,",
    "          'clientId': clientId,",
    "          'invoiceId': invoiceId,",
    "          'amount': paidAmount,",
    "          'receiptDate': invoiceDate.toIso8601String(),",
    "          'note': null,",
    "          'status': RecordStatus.ACTIVE.index,",
    "          'voidReason': null,",
    "          'createdAt': now.toIso8601String(),",
    "          'updatedAt': now.toIso8601String(),",
    "          'deviceId': deviceId,",
    "          'rowVersion': 1,",
    "          'syncStatus': SyncStatus.PENDING.index,",
    "        });",
    "",
    "        await _db.into(_db.receipts).insert(",
    "          ReceiptsCompanion(",
    "            id: Value(receiptId),",
    "            receiptType: Value(ReceiptType.INVOICE_LINKED),",
    "            clientId: Value(clientId),",
    "            invoiceId: Value(invoiceId),",
    "            amount: Value(paidAmount),",
    "            receiptDate: Value(invoiceDate),",
    "            note: Value.absent(),",
    "            status: Value(RecordStatus.ACTIVE),",
    "            voidReason: Value.absent(),",
    "            createdAt: Value(now),",
    "            updatedAt: Value(now),",
    "            deviceId: Value(deviceId),",
    "            rowVersion: const Value(1),",
    "            syncStatus: Value(SyncStatus.PENDING),",
    "          ),",
    "        );",
    "",
    "        final allocationId = _uuid.v4();",
    "        await _db.into(_db.receiptAllocations).insert(",
    "          ReceiptAllocationsCompanion(",
    "            id: Value(allocationId),",
    "            receiptId: Value(receiptId),",
    "            invoiceId: Value(invoiceId),",
    "            allocatedAmount: Value(paidAmount),",
    "            createdAt: Value(now),",
    "            updatedAt: Value(now),",
    "          ),",
    "        );",
    "",
    "        await _db.into(_db.syncOutbox).insert(",
    "          SyncOutboxCompanion.insert(",
    "            id: _uuid.v4(),",
    "            entityType: ParentEntityType.RECEIPT,",
    "            entityId: receiptId,",
    "            operation: AuditOperation.CREATE,",
    "            payload: receiptPayload,",
    "            rowVersion: 1,",
    "            deviceId: deviceId,",
    "            createdAt: now,",
    "            status: Value(SyncOutboxStatus.PENDING),",
    "          ),",
    "        );",
    "",
    "        final allocPayload = jsonEncode({",
    "          'id': allocationId,",
    "          'receiptId': receiptId,",
    "          'invoiceId': invoiceId,",
    "          'allocatedAmount': paidAmount,",
    "          'createdAt': now.toIso8601String(),",
    "          'updatedAt': now.toIso8601String(),",
    "        });",
    "        await _db.into(_db.syncOutbox).insert(",
    "          SyncOutboxCompanion.insert(",
    "            id: _uuid.v4(),",
    "            entityType: ParentEntityType.RECEIPT_ALLOCATION,",
    "            entityId: allocationId,",
    "            operation: AuditOperation.CREATE,",
    "            payload: allocPayload,",
    "            rowVersion: 1,",
    "            deviceId: deviceId,",
    "            createdAt: now,",
    "            status: Value(SyncOutboxStatus.PENDING),",
    "          ),",
    "        );",
    "      }",
    "    });",
    "",
    "    return await getById(invoiceId);",
    "  }",
]

# --- T003: query methods ---
lines += [
    "",
    "  Future<SalesInvoice> getById(String id) async {",
    "    return (_db.select(_db.salesInvoices)..where((t) => t.id.equals(id)))",
    "        .getSingle();",
    "  }",
    "",
    "  Stream<List<SalesInvoice>> watchAll() {",
    "    return (_db.select(_db.salesInvoices)",
    "          ..orderBy([",
    "            (t) => OrderingTerm.desc(t.invoiceDate),",
    "            (t) => OrderingTerm.desc(t.createdAt),",
    "          ])).watch();",
    "  }",
    "",
    "  Future<List<SalesInvoiceLine>> getLinesForInvoice(String invoiceId) async {",
    "    return (_db.select(_db.salesInvoiceLines)",
    "          ..where((t) => t.invoiceId.equals(invoiceId))).get();",
    "  }",
    "",
    "  Future<List<Receipt>> getReceiptsForInvoice(String invoiceId) async {",
    "    return (_db.select(_db.receipts)",
    "          ..where((t) =>",
    "              t.invoiceId.equals(invoiceId) &",
    "              t.status.equals(RecordStatus.ACTIVE.index))).get();",
    "  }",
    "",
    "  Future<int> getCollectedAmount(String invoiceId) async {",
    "    final row = await _db.customSelect(",
    "      'SELECT COALESCE(SUM(ra.allocated_amount), 0) AS collected '",
    "      'FROM receipt_allocations ra '",
    "      'INNER JOIN receipts r ON ra.receipt_id = r.id '",
    "      'WHERE ra.invoice_id = ? AND r.status = ?',",
    "      variables: [",
    "        Variable(invoiceId),",
    "        Variable(RecordStatus.ACTIVE.index),",
    "      ],",
    "    ).getSingle();",
    "    return row.read<int>('collected');",
    "  }",
    "",
    "  Future<int> getRemainingBalance(String invoiceId) async {",
    "    final invoice = await getById(invoiceId);",
    "    final collected = await getCollectedAmount(invoiceId);",
    "    return invoice.total - collected;",
    "  }",
    "",
    "  Future<bool> hasActiveReceipts(String invoiceId) async {",
    "    final row = await _db.customSelect(",
    "      'SELECT COUNT(*) AS cnt FROM receipts '",
    "      'WHERE invoice_id = ? AND status = ?',",
    "      variables: [",
    "        Variable(invoiceId),",
    "        Variable(RecordStatus.ACTIVE.index),",
    "      ],",
    "    ).getSingle();",
    "    return row.read<int>('cnt') > 0;",
    "  }",
    "",
    "  Future<bool> hasActiveReturns(String invoiceId) async {",
    "    final row = await _db.customSelect(",
    "      'SELECT COUNT(*) AS cnt FROM sales_returns '",
    "      'WHERE invoice_id = ? AND status = ?',",
    "      variables: [",
    "        Variable(invoiceId),",
    "        Variable(RecordStatus.ACTIVE.index),",
    "      ],",
    "    ).getSingle();",
    "    return row.read<int>('cnt') > 0;",
    "  }",
]

# --- T004: update + updateNote methods ---
lines += [
    "",
    "  Future<void> update({",
    "    required String id,",
    "    required String clientId,",
    "    required DateTime invoiceDate,",
    "    required int discount,",
    "    required String? note,",
    "    required List<SalesInvoiceLinesCompanion> lines,",
    "    required String deviceId,",
    "  }) async {",
    "    final existing = await getById(id);",
    "",
    "    if (existing.status == RecordStatus.VOIDED) {",
    "      throw StateError('Cannot update a voided invoice');",
    "    }",
    "",
    "    if (await hasActiveReturns(id)) {",
    "      throw StateError(",
    "        'Cannot update invoice with active returns. Use updateNote instead.',",
    "      );",
    "    }",
    "",
    "    if (lines.isEmpty) {",
    "      throw ArgumentError('Invoice must have at least one line');",
    "    }",
    "",
    "    var subtotal = 0;",
    "    final preparedLines = <SalesInvoiceLinesCompanion>[];",
    "    for (final line in lines) {",
    "      final qty = line.quantity.present ? line.quantity.value : 1;",
    "      final price = line.unitPrice.present ? line.unitPrice.value : 0;",
    "      final lineTotal = qty * price;",
    "      preparedLines.add(line.copyWith(",
    "        lineTotal: Value(lineTotal),",
    "      ));",
    "      subtotal += lineTotal;",
    "    }",
    "",
    "    if (discount > subtotal) {",
    "      throw ArgumentError('Discount cannot exceed subtotal');",
    "    }",
    "",
    "    final total = subtotal - discount;",
    "",
    "    if (await hasActiveReceipts(id)) {",
    "      final collectedAmount = await getCollectedAmount(id);",
    "      if (total < collectedAmount) {",
    "        throw ArgumentError(",
    "          'Total cannot be less than collected amount ($collectedAmount)',",
    "        );",
    "      }",
    "    }",
    "",
    "    final now = DateTime.now();",
    "    final newVersion = existing.rowVersion + 1;",
    "",
    "    await _db.transaction(() async {",
    "      await (_db.delete(_db.salesInvoiceLines)",
    "            ..where((t) => t.invoiceId.equals(id))).go();",
    "",
    "      for (final line in preparedLines) {",
    "        final lineId = _uuid.v4();",
    "        await _db.into(_db.salesInvoiceLines).insert(",
    "          line.copyWith(",
    "            id: Value(lineId),",
    "            invoiceId: Value(id),",
    "            createdAt: Value(now),",
    "            updatedAt: Value(now),",
    "          ),",
    "        );",
    "",
    "        final linePayload = jsonEncode({",
    "          'id': lineId,",
    "          'invoiceId': id,",
    "          'productId': line.productId.present ? line.productId.value : null,",
    "          'quantity': line.quantity.present ? line.quantity.value : null,",
    "          'unitPrice': line.unitPrice.present ? line.unitPrice.value : null,",
    "          'lineTotal': line.lineTotal.present ? line.lineTotal.value : null,",
    "          'createdAt': now.toIso8601String(),",
    "          'updatedAt': now.toIso8601String(),",
    "        });",
    "        await _db.into(_db.syncOutbox).insert(",
    "          SyncOutboxCompanion.insert(",
    "            id: _uuid.v4(),",
    "            entityType: ParentEntityType.SALES_INVOICE_LINE,",
    "            entityId: lineId,",
    "            operation: AuditOperation.CREATE,",
    "            payload: linePayload,",
    "            rowVersion: newVersion,",
    "            deviceId: deviceId,",
    "            createdAt: now,",
    "            status: Value(SyncOutboxStatus.PENDING),",
    "          ),",
    "        );",
    "      }",
    "",
    "      await (_db.update(_db.salesInvoices)",
    "            ..where((t) => t.id.equals(id))).write(",
    "        SalesInvoicesCompanion(",
    "          clientId: Value(clientId),",
    "          invoiceDate: Value(invoiceDate),",
    "          discount: Value(discount),",
    "          total: Value(total),",
    "          note: Value(note),",
    "          updatedAt: Value(now),",
    "          rowVersion: Value(newVersion),",
    "          syncStatus: Value(SyncStatus.PENDING),",
    "        ),",
    "      );",
    "",
    "      final invoicePayload = jsonEncode({",
    "        'id': id,",
    "        'localRef': existing.localRef,",
    "        'officialNo': existing.officialNo,",
    "        'clientId': clientId,",
    "        'invoiceDate': invoiceDate.toIso8601String(),",
    "        'discount': discount,",
    "        'total': total,",
    "        'note': note,",
    "        'status': existing.status.index,",
    "        'voidReason': existing.voidReason,",
    "        'createdAt': existing.createdAt.toIso8601String(),",
    "        'updatedAt': now.toIso8601String(),",
    "        'deviceId': deviceId,",
    "        'rowVersion': newVersion,",
    "        'syncStatus': SyncStatus.PENDING.index,",
    "      });",
    "      await _db.into(_db.syncOutbox).insert(",
    "        SyncOutboxCompanion.insert(",
    "          id: _uuid.v4(),",
    "          entityType: ParentEntityType.SALES_INVOICE,",
    "          entityId: id,",
    "          operation: AuditOperation.UPDATE,",
    "          payload: invoicePayload,",
    "          rowVersion: newVersion,",
    "          deviceId: deviceId,",
    "          createdAt: now,",
    "          status: Value(SyncOutboxStatus.PENDING),",
    "        ),",
    "      );",
    "    });",
    "  }",
    "",
    "  Future<void> updateNote(String id, String? note, String deviceId) async {",
    "    final existing = await getById(id);",
    "",
    "    if (existing.status == RecordStatus.VOIDED) {",
    "      throw StateError('Cannot update a voided invoice');",
    "    }",
    "",
    "    final now = DateTime.now();",
    "    final newVersion = existing.rowVersion + 1;",
    "",
    "    await _db.transaction(() async {",
    "      await (_db.update(_db.salesInvoices)",
    "            ..where((t) => t.id.equals(id))).write(",
    "        SalesInvoicesCompanion(",
    "          note: Value(note),",
    "          updatedAt: Value(now),",
    "          rowVersion: Value(newVersion),",
    "          syncStatus: Value(SyncStatus.PENDING),",
    "        ),",
    "      );",
    "",
    "      final invoicePayload = jsonEncode({",
    "        'id': id,",
    "        'localRef': existing.localRef,",
    "        'officialNo': existing.officialNo,",
    "        'clientId': existing.clientId,",
    "        'invoiceDate': existing.invoiceDate.toIso8601String(),",
    "        'discount': existing.discount,",
    "        'total': existing.total,",
    "        'note': note,",
    "        'status': existing.status.index,",
    "        'voidReason': existing.voidReason,",
    "        'createdAt': existing.createdAt.toIso8601String(),",
    "        'updatedAt': now.toIso8601String(),",
    "        'deviceId': existing.deviceId,",
    "        'rowVersion': newVersion,",
    "        'syncStatus': SyncStatus.PENDING.index,",
    "      });",
    "      await _db.into(_db.syncOutbox).insert(",
    "        SyncOutboxCompanion.insert(",
    "          id: _uuid.v4(),",
    "          entityType: ParentEntityType.SALES_INVOICE,",
    "          entityId: id,",
    "          operation: AuditOperation.UPDATE,",
    "          payload: invoicePayload,",
    "          rowVersion: newVersion,",
    "          deviceId: deviceId,",
    "          createdAt: now,",
    "          status: Value(SyncOutboxStatus.PENDING),",
    "        ),",
    "      );",
    "    });",
    "  }",
]

# --- T005: voidInvoice method ---
lines += [
    "",
    "  Future<void> voidInvoice(String id, String reason, String deviceId) async {",
    "    if (reason.trim().isEmpty) {",
    "      throw ArgumentError('Void reason is required');",
    "    }",
    "",
    "    final existing = await getById(id);",
    "",
    "    if (existing.status == RecordStatus.VOIDED) {",
    "      throw StateError('Invoice is already voided');",
    "    }",
    "",
    "    final now = DateTime.now();",
    "    final newVersion = existing.rowVersion + 1;",
    "",
    "    await _db.transaction(() async {",
    "      final allocRows = await _db.customSelect(",
    "        'SELECT ra.receipt_id AS receipt_id '",
    "        'FROM receipt_allocations ra '",
    "        'INNER JOIN receipts r ON ra.receipt_id = r.id '",
    "        'WHERE ra.invoice_id = ? AND r.status = ?',",
    "        variables: [",
    "          Variable(id),",
    "          Variable(RecordStatus.ACTIVE.index),",
    "        ],",
    "      ).get();",
    "",
    "      final affectedReceiptIds =",
    "          allocRows.map((r) => r.read<String>('receipt_id')).toSet();",
    "",
    "      await (_db.delete(_db.receiptAllocations)",
    "            ..where((t) => t.invoiceId.equals(id))).go();",
    "",
    "      await (_db.update(_db.salesInvoices)",
    "            ..where((t) => t.id.equals(id))).write(",
    "        SalesInvoicesCompanion(",
    "          status: Value(RecordStatus.VOIDED),",
    "          voidReason: Value(reason),",
    "          updatedAt: Value(now),",
    "          rowVersion: Value(newVersion),",
    "          syncStatus: Value(SyncStatus.PENDING),",
    "        ),",
    "      );",
    "",
    "      final invoicePayload = jsonEncode({",
    "        'id': id,",
    "        'localRef': existing.localRef,",
    "        'officialNo': existing.officialNo,",
    "        'clientId': existing.clientId,",
    "        'invoiceDate': existing.invoiceDate.toIso8601String(),",
    "        'discount': existing.discount,",
    "        'total': existing.total,",
    "        'note': existing.note,",
    "        'status': RecordStatus.VOIDED.index,",
    "        'voidReason': reason,",
    "        'createdAt': existing.createdAt.toIso8601String(),",
    "        'updatedAt': now.toIso8601String(),",
    "        'deviceId': existing.deviceId,",
    "        'rowVersion': newVersion,",
    "        'syncStatus': SyncStatus.PENDING.index,",
    "      });",
    "      await _db.into(_db.syncOutbox).insert(",
    "        SyncOutboxCompanion.insert(",
    "          id: _uuid.v4(),",
    "          entityType: ParentEntityType.SALES_INVOICE,",
    "          entityId: id,",
    "          operation: AuditOperation.UPDATE,",
    "          payload: invoicePayload,",
    "          rowVersion: newVersion,",
    "          deviceId: deviceId,",
    "          createdAt: now,",
    "          status: Value(SyncOutboxStatus.PENDING),",
    "        ),",
    "      );",
    "",
    "      if (affectedReceiptIds.isNotEmpty) {",
    "        final allocator = ReceiptAllocator(_db);",
    "",
    "        for (final receiptId in affectedReceiptIds) {",
    "          final receipt = await (_db.select(_db.receipts)",
    "                ..where((t) => t.id.equals(receiptId))).getSingle();",
    "",
    "          final newAllocations = await allocator.allocateFifo(",
    "            existing.clientId,",
    "            receipt.amount,",
    "            excludeInvoiceId: id,",
    "          );",
    "",
    "          for (final alloc in newAllocations) {",
    "            final allocWithReceipt = alloc.copyWith(",
    "              receiptId: Value(receiptId),",
    "            );",
    "            await _db.into(_db.receiptAllocations).insert(allocWithReceipt);",
    "",
    "            final allocId = allocWithReceipt.id.value;",
    "            final allocPayload = jsonEncode({",
    "              'id': allocId,",
    "              'receiptId': receiptId,",
    "              'invoiceId': allocWithReceipt.invoiceId.value,",
    "              'allocatedAmount': allocWithReceipt.allocatedAmount.value,",
    "              'createdAt': now.toIso8601String(),",
    "              'updatedAt': now.toIso8601String(),",
    "            });",
    "            await _db.into(_db.syncOutbox).insert(",
    "              SyncOutboxCompanion.insert(",
    "                id: _uuid.v4(),",
    "                entityType: ParentEntityType.RECEIPT_ALLOCATION,",
    "                entityId: allocId,",
    "                operation: AuditOperation.CREATE,",
    "                payload: allocPayload,",
    "                rowVersion: 1,",
    "                deviceId: deviceId,",
    "                createdAt: now,",
    "                status: Value(SyncOutboxStatus.PENDING),",
    "              ),",
    "            );",
    "          }",
    "        }",
    "      }",
    "    });",
    "  }",
    "}",
]

content = '\n'.join(lines) + '\n'

outpath = r'D:\Motaz_App2\motaz_app\motaz_app_flutter\lib\features\invoices\data\invoice_repository.dart'
os.makedirs(os.path.dirname(outpath), exist_ok=True)

with open(outpath, 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)

print('T002-T005 invoice_repository.dart written successfully.')
