FROM dart:stable

WORKDIR /app

# Copy only backend packages.
# Do NOT copy Flutter app because it requires Flutter SDK.
COPY motaz_app_client ./motaz_app_client
COPY motaz_app_server ./motaz_app_server

# Install Serverpod CLI.
# IMPORTANT: keep this version aligned with your serverpod package version.
RUN dart pub global activate serverpod_cli 3.4.7

ENV PATH="/root/.pub-cache/bin:${PATH}"

# Serverpod generation must happen before running the server.
WORKDIR /app/motaz_app_server

RUN dart pub get

RUN serverpod generate

EXPOSE 8080

CMD ["sh", "-c", "export SERVERPOD_API_SERVER_PORT=${PORT:-8080}; dart bin/main.dart --mode production"]