FROM dart:stable

WORKDIR /app

COPY . .

WORKDIR /app/motaz_app_server

RUN dart pub get

EXPOSE 8080

CMD ["sh", "-c", "export SERVERPOD_API_SERVER_PORT=${PORT:-8080}; dart bin/main.dart --mode production"]